### ISSUE TITLE
InfluxDB Connector Issue

### ISSUE THREAD

**Issue by wallyhk** [influxdata/influxdb-gds-connector#15]
I'm trying to understand this error more when I try to authorize the connector. Is anyone able to advise?

"GetBuckets from: https://xxx.xxx.com/" returned an error:Exception: Could not parse text.

**Comment by bednar** [comment]
Hi @wallyhk,

thanks for using our GDS connector.

It looks like a query to look up of all buckets in your InfluxDB failed. 

Can you share the output of following query?

```flux
buckets() |> rename(columns: {"name": "_value"}) |> keep(columns: ["_value"]) |> sort(columns: ["_value"], desc: false)
```

Regards
