### ISSUE TITLE
GDS Connector not found

### ISSUE THREAD

**Issue by alexmc1510** [influxdata/influxdb-gds-connector#18]
Hello,

I know what I will report is not a real issue but I don't know where I should open it. Please let me know and I will move the post wherever you say. Mine is a simple question. I am not able to find the connector in GDS. Has it been retired? Should I install something or suscribe somewhere?

Thanks in advance

**Comment by bednar** [comment]
Hi @alexmc1510,

thanks for using our connector.

You can use a button at GitHub's `README.md`:

![image](https://user-images.githubusercontent.com/455137/154902473-de73999f-2a23-4abd-a2a5-3547d66c75a7.png)

or following link:

https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbwhJChhmMypQvNlihgRJMAhCb8gaM3ii9oUNWlW_Cp2PbJSfqeHfPyjNVp15iy9ltCs

Regards

**Comment by alexmc1510** [comment]
Hi. There is an error when trying to add the connector.
![Captura2](https://user-images.githubusercontent.com/36837980/154904676-531d7a23-9047-4358-98a3-1d409baff610.PNG)
![Captura](https://user-images.githubusercontent.com/36837980/154904681-dd082c80-6093-4684-91bb-de736b0c9d75.PNG)


Regards
