### ISSUE TITLE
Metric data type can not be changed back to it's original data type.

### ISSUE THREAD

**Issue by ph5ive** [influxdata/influxdb-gds-connector#22]
__The issue:__

I noticed that if you change the metrics data type from 'Date & Time' to 'Text' you can't change it back. 

<img width="770" alt="Before" src="https://user-images.githubusercontent.com/16837178/169836574-24163ea9-08dd-42e8-9c2a-d44fc3b3a8b9.png">

This is because the 'Date & Time' option is no longer available in the LOVs. 

<img width="792" alt="After" src="https://user-images.githubusercontent.com/16837178/169836648-b0b32e58-e646-4168-90fe-ca9abbfd0714.png">

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Using GDS create a connection to InfluxData Cloud2 service, setting the InfluxDB URL, Token, Organisation, Bucket and Measurement.
2. ... Within GDS, at the field editing section, change the 'time' metric data type from 'Date & Time' to data type  'Text'.
3. ... Now, try to change it back from 'Text' to a 'Date & Time'.

__Expected behavior:__
You should be able to change the data type back using the LOVs.

__Actual behavior:__
The original data type of 'Date & Time' is no longer available in the LOVs.

__Specifications:__
 - Client Version: 2021.10
 - InfluxDB Version: 2.x Cloud
 - Platform: n/a

**Comment by bednar** [comment]
Hi @ph5ive,

thanks for using our connector.

The values available in LOVs are controlled by GDS. According to the following docs, the column with AUTO aggregation cannot be change:

![image](https://user-images.githubusercontent.com/455137/169971756-486d54f0-041c-4ae5-8793-134f7f792585.png)

- https://support.google.com/datastudio/answer/7512288

I have to investigate how we define the `time` metrics and if we need to change something here:

- https://developers.google.com/datastudio/connector/reference#field
- https://github.com/influxdata/influxdb-gds-connector/blob/c035907cd9bfff498ce39544968c65e5dc03991d/src/InfluxDBClient.js#L202

Regards

**Comment by bednar** [comment]
We have to set the `defaultAggregationType` config for the `time` to `false`. After that the `time` will be `dimension` (green) type and the LOVs will contains full range of types.

- https://support.google.com/datastudio/answer/6402048?ref_topic=7441655#zippy=%2Cin-this-article
- https://support.google.com/datastudio/thread/18307022
- https://stackoverflow.com/a/66858872

The "blue" is supposed to use for fields with pre-aggregated values.
