### ISSUE TITLE
InfluxDB Connector Issue

### ISSUE THREAD

**Issue by timothy-franklin** [influxdata/influxdb-gds-connector#24]
Hi - Trying to use InfluxDB connector to connect to our Azure Tenant hosted InfluxDB 2.1.1 instance. The connector authorization throws an error when I provide the URL, Token Org.  I took the query it was running and ran it as a query in the Data Explorer on that instance and it didn't return an error. I know the url, token are correct because I use that same info to connect from Redash.   Any thoughts? Version compatability?
![Screen Shot 2022-06-03 at 9 34 23 AM](https://user-images.githubusercontent.com/78759016/171876034-25c869df-1b74-4f03-b1d8-c75c972f0919.png)
<img width="1453" alt="Screen Shot 2022-06-03 at 9 34 11 AM" src="https://user-images.githubusercontent.com/78759016/171876037-55cb512a-1300-4f4e-85b1-7db0ecb286c5.png">

**Comment by bednar** [comment]
Hi @timothy-franklin,

thanks for using our connecter.

Please double check that you enter correct name of `organization` and `bucket`. You can use following script to check your settings:

```
curl --request POST 'http://localhost:8086/api/v2/query?org=INFLUX_ORG' \
  --header 'Authorization: Token INFLUX_TOKEN' \
  --header 'Accept: application/csv' \
  --header 'Content-type: application/vnd.flux' \
  --data 'buckets()
        |> rename(columns: {"name": "_value"})
        |> keep(columns: ["_value"])
        |> sort(columns: ["_value"], desc: false)'
```


Regards.
