### ISSUE TITLE
Metrics and Dimensions are imported around the wrong way

### ISSUE THREAD

**Issue by BeenFifteen** [influxdata/influxdb-gds-connector#6]
Currently when data is imported into data studio from InfluxDB, time is imported as a metric (blue) while the metrics are imported as dimensions (green). This should be the opposite way round and currently makes this unusable.

**Comment by bednar** [comment]
Hi @BeenFifteen,

thanks for using our connector.

I think that the mapping highly depend on your InfluxDB schema. The connector is not able to know how was your field aggregated. 

The metrics could be use as a source for aggregated operation:

Schema:
![image](https://user-images.githubusercontent.com/455137/96541681-d0147100-12a0-11eb-8c1b-ee171b8e5966.png)

Aggregated function over metrics:
![image](https://user-images.githubusercontent.com/455137/96541613-b5da9300-12a0-11eb-95d8-116e744a980b.png)

For more info see our example: https://github.com/influxdata/influxdb-gds-connector/tree/master/examples

If this setting doesn't fit your requirements, Could you please share a little bit more info about your InfluxDB schema and how you want to use it in Google Data Studio?

Regards

**Comment by BeenFifteen** [comment]
Hi bednar,

Thanks for the quick reply and for everything you've done on this connector.

Currently I am simply trying to begin with a basic weather station dashboard using my weather station information stored on influxdb.
The first thing I wanted to implement was a time-series chart so I tried to set it up as follows.

![image](https://user-images.githubusercontent.com/69996336/96572174-03024780-1329-11eb-845b-6ebbcb08e909.png)

But as can be seen above it couldn't be done.
Other time-series charts get set-up as seen in the example following with time being the dimension, and the other fields being metrics.

![image](https://user-images.githubusercontent.com/69996336/96571476-1c56c400-1328-11eb-9d67-30840e68701e.png)

Is this an issue with my InfluxDB field setup or with the connector?

Thanks

**Comment by bednar** [comment]
You are able to change how you visualise your data. Just change dimension to `time` and as a metric add `Avarage of temperature_C`.

**Comment by BeenFifteen** [comment]
I was able to shift a dimension to be a metric as you recommended. But the metric of time doesn't appear to be able to be set as a dimension even when setting it up time as a custom field.

**Comment by BeenFifteen** [comment]
Hi Bednar, 

I was able to set time as a metric through the custom field.

![image](https://user-images.githubusercontent.com/69996336/96579039-aad04300-1332-11eb-884a-e2c4966c819c.png)

Thanks for your help.

**Comment by bednar** [comment]
You could use `TODATE` function:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/455137/96584323-57cca080-12de-11eb-9168-10f91c73f9a3.png">

**Comment by max-mykhailenko** [comment]
Works for me 

Formula for new calculated time dimension
`TODATE(time, '%Y-%m-%d %H:%M:%S', '%Y%m%d%H%M')`

![image](https://user-images.githubusercontent.com/1213198/122521380-6d38cc80-d01d-11eb-809f-6d3702c147d0.png)
