### ISSUE TITLE
InfluxDB Connector Issue

### ISSUE THREAD

**Issue by gefaila** [influxdata/influxdb-gds-connector#8]
Very excited to try this connector.
I have a bucket with a lot of data in.  It seemed to make the connector 'fall over'

>Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

>Connector details
"GetFields from: https://eu-central-1-1.aws.cloud2.influxdata.com" returned an error:Exception: Request failed for https://eu-central-1-1.aws.cloud2.influxdata.com returned code 400. Truncated server response: {"code":"invalid","message":"runtime error @1:110-1:143: drop: schema collision detected: column \"_value\" is both of type int and float"} (use muteHttpExceptions option to examine full response)

>Error ID: fb5b13d2

I'm quite experienced on InfluxDB and there is nothing fundamentally wrong with having _value as being int and float for different _field values.  In fact it's fairly fundamental.  There must be something that the connector is assuming about InfluxDB 2.0 data that is (in general) not always true.

Any ideas how I'd move forward to use this excellent tool?

**Comment by bednar** [comment]
Hi @gefaila,

> I'm quite experienced on InfluxDB and there is nothing fundamentally wrong with having _value as being int and float for different _field values. 

Yes, but Google Data Studio requires _static_ schema. The connector internally uses pivot function to determine schema for GDS.

Schema query:
```
from(bucket: "my-bucket") 
    |> range(start: time(v: 1)) 
    |> filter(fn: (r) => r["_measurement"] == "circleci") 
    |> drop(columns: ["tag1", "tag2", "tag3"]) 
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
    |> drop(columns: ["_start", "_stop", "_time", "_measurement"]) 
    |> limit(n:1)
```

You could prepare Task that normalize your data into new Measurement. See - https://github.com/influxdata/influxdb-gds-connector/tree/master/examples#performance

Regards

**Comment by gefaila** [comment]
Hi @bednar, 
Thanks for engaging here!  👍 

The Schema query runs fine on the data in my bucket, 
It produces a table each of the hosts I have in the database.

[2020-11-09-10-50_chronograf_data.xlsx](https://github.com/influxdata/influxdb-gds-connector/files/5509879/2020-11-09-10-50_chronograf_data.xlsx)

Is there anything wrong with this data it's returning to GDS?

If, not, are there any documented guidelines for what this data should conform to?

I checked out the link you sent above 

> You could prepare Task that normalize your data into new Measurement. See - https://github.com/influxdata/influxdb-gds-connector/tree/master/examples#performance

However, there is no actual definition of acceptable and unacceptable data, Just a single example of a very long flux query that is apparently returning something that is OK for GDS.

Maybe some clarification is needed for the general case?
Thanks

**Comment by bednar** [comment]
Hi @gefaila,

The schema query should produce only one table, because the GDS needs consistent schema.

Based on your export `2020-11-09-10-50_chronograf_data.xlsx` you missed add dropping of tags. Try this:

```flux
bucket = "my-bucket"
measurement = "my-measurement"
tags = ["host", "method"]

from(bucket: bucket) 
    |> range(start: time(v: 1)) 
    |> filter(fn: (r) => r["_measurement"] == measurement) 
    |> drop(columns: tags) 
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
    |> drop(columns: ["_start", "_stop", "_time", "_measurement"]) 
    |> limit(n:1)
```

You could find all your tags by:

```flux
import "influxdata/influxdb/v1"

bucket = "my-bucket"
measurement = "gds"

v1.tagKeys(
  bucket: bucket,
  predicate: (r) => r._measurement == measurement,
  start: duration(v: uint(v: 1970-01-01) - uint(v: now()))
)
|> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
```

> However, there is no actual definition of acceptable and unacceptable data, Just a single example of a very long flux query that is apparently returning something that is OK for GDS.
>
> Maybe some clarification is needed for the general case?

Yeah, you are right. We need clarify how to data should looks like to use in GDS.

Could you export result of schema query to CSV?

Regards.

**Comment by gefaila** [comment]
> Could you export result of schema query to CSV?
It's above as an xlsx because git doesn't like csvs  
👍

**Comment by gefaila** [comment]
Actually, even better would be to allow the user to write a flux query that returned data in the format GDS needs it.

**Comment by bednar** [comment]
> Furthermore, the querying of InfluxDB data with `from(bucket: "my-bucket") |> range(start: time(v: 1))` is not great. 

The query with this `range(start: time(v: 1))` is only used for determine the schema. 

For getting data we use range specified in report - https://support.google.com/datastudio/answer/9272806?hl=en. By default, the date range provided will be the last 28 days excluding today. If a user applies a date range filter for a report, then the date range provided will reflect the user selection.

> A good way of giving the user the ability to make sure the data returned was suitable for GDS would be to allow the user to write a flux query that returned data in the format GDS needs it. E.g. one table with agreed structure.

We use two type of queries: 

#### GetSchema

- call only once

```flux
from(bucket:"my-bucket") 
    |> range(start: time(v: 1)) 
    |> filter(fn: (r) => r["_measurement"] == "my-measurement") 
    |> drop(columns: tags) 
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
    |> drop(columns: ["_start", "_stop", "_time", "_measurement"]) 
    |> limit(n:1)
```

#### GetData

- range is determined by GDS Filter

```flux
from(bucket: "my-bucket") 
   |> range(start: 2020-04-20T00:00:00Z, stop: 2020-05-20T23:59:59Z)
   |> filter(fn: (r) => r["_measurement"] == "my-measurement") 
   |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

What do you think about ability to specify _Flux filter_? 

You will be able to specify something like: `r["host"] == "R1901_1742"` and this _Flux filter_ will be append after `|> filter(fn: (r) => r["_measurement"] == "my-measurement")` in *GetSchema* and *GetData* queries.

Regards

**Comment by gefaila** [comment]
However, stepping back a bit, I see no reason why I would not want to build a dashboard that allowed the filtering to happen 'afterwards'.  Again, this is parallel to the Chronograf dashboards with a variable.

On one of my dashboards I can select the host that I'm interested in viewing.
![image](https://user-images.githubusercontent.com/69196723/98814928-4c245380-241e-11eb-85cb-af4227a19d59.png)

To me that seems much more sensible and usable functionality to aim for in GDS.

What do you think?
Possible?
👍

**Comment by bednar** [comment]
> What do you think?
> Possible?

Yeah, of course. We use this type of filter here: https://datastudio.google.com/s/p19vh-b82Sw - "Country Filter".

Do you think that update our docs to clarify required schema for GDS will be enough? Something like:

### Required schema

The Google Data Studio requires know schema of your data. Each column requires a data type that should be consistent across whole table (= measurement in InfluxDB). For that reason the **InfluxDB Connector** needs to determine schema from your InfluxDB by this `Flux` query:

```flux
import "influxdata/influxdb/v1"

bucket = "my-bucket"
measurement = "my-measurement"

tags = v1.tagKeys(
  bucket: bucket,
  predicate: (r) => r._measurement == measurement,
  start: duration(v: uint(v: 1970-01-01) - uint(v: now()))
) |> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
  |> findColumn(fn: (key) => true, column: "_value")

from(bucket: bucket) 
  |> range(start: time(v: 1)) 
  |> filter(fn: (r) => r["_measurement"] == measurement) 
  |> drop(fn: (column) => contains(value: column, set: tags))
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
  |> drop(columns: ["_start", "_stop", "_time", "_measurement"]) 
  |> limit(n:1)
```

Please be ensure that the query above could be successfully use in your InfluxDB.

#### Links

- https://developers.google.com/datastudio/connector/semantics

Regrads

**Comment by gefaila** [comment]
> What do you think about ability to specify Flux filter?

>You will be able to specify something like: r["host"] == "R1901_1742" and this Flux filter will be append after |> filter(fn: (r) => r["_measurement"] == "my-measurement") in GetSchema and GetData queries.

Well I don't see why it's necessary for the user to specify flux filters.

You've already confirmed that filtering is possible after building the dashboard

>Yeah, of course. We use this type of filter here: https://datastudio.google.com/s/p19vh-b82Sw - "Country Filter".

So why compel the user to filter so that you can even make a connection!

The fact is that a normal bucket will contain data with multiple tags.  Therefore your schema will not normally work.
What the user would obviously like is to be able to build a GDS dashboard from the data they have.
They don't want to have to create copies of the data in other buckets, simply because GDS can't cope with multiple tags.

**Comment by gefaila** [comment]
> Do you think that update our docs to clarify required schema for GDS will be enough? Something like:

>Required schema
>The Google Data Studio requires know schema of your data. Each column requires a data type that should be consistent across whole table (= measurement in InfluxDB). For that reason the InfluxDB Connector needs to determine schema from your InfluxDB by this Flux query:

No not really.
I'd just like the GDS to work on my InfluxDB tables as-is.

**Comment by gefaila** [comment]
If you like, I can give you a key with read access to my bucket. 
Whatever the  GDS schema, it should work with normal  influx data with a variety of tags in.
And that is what my bucket is.

**Comment by gefaila** [comment]
What I don't quite understand is the actual tags that GDS doesn't like in my data tables.  And I can't run the flux query you specify for the reasons I give above.  i.e. you are forcing a search through all data from 1970 to current day.  Apart from the fact that this takes longer than the timeout, the query will in most cases run out of memory. It's impossible in the general case where people are using InfluxDB for what it's designed for GB of data every day.

**Comment by gefaila** [comment]
I can only get the flux query to run by considering less time:

> import "influxdata/influxdb/v1"

>bucket = "PLC_Router_Data"
>measurement = "data"

>tags = v1.tagKeys(
> bucket: bucket,
>  predicate: (r) => r._measurement == measurement,
 > start: -3d
>) |> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
 > |> findColumn(fn: (key) => true, column: "_value")

>from(bucket: bucket) 
 > |> range(start: -3d) 
  >|> filter(fn: (r) => r["_measurement"] == measurement) 
  >|> drop(fn: (column) => contains(value: column, set: tags))
  >|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
  >|> drop(columns: ["_start", "_stop", "_time", "_measurement"]) 
  >|> limit(n:1)

Then this delivers a single table

Even querying 30d causes InfluxDB  cloud to run out of memory. This will be the case for most customers who have significant data in their tables

**Comment by gefaila** [comment]
Querying 30days runs out of memory
Imagine querying 300 days.
You can forget 3000 days.
But your flux query goes through 18,578 days!!!!
You've got to be kidding

**Comment by bednar** [comment]
> What I don't quite understand is the actual tags that GDS doesn't like in my data tables. 

The `schema collision detected: column "_value" is both of type int and float"` is response from InfluxDB to the schema query.

> And I can't run the flux query you specify for the reasons I give above. i.e. you are forcing a search through all data from 1970 to current day. Apart from the fact that this takes longer than the timeout, the query will in most cases run out of memory. It's impossible in the general case where people are using InfluxDB for what it's designed for GB of data every day.

The key problem here is that the Flux doesn't have [`show-field-keys`](https://docs.influxdata.com/influxdb/v1.8/query_language/schema_exploration/#show-field-keys) as IFQL. The our schema query is just workaround for this.

> Querying 30days runs out of memory
Imagine querying 300 days.
You can forget 3000 days.
But your flux query goes through 18,578 days!!!!
You've got to be kidding

Yes, it scan whole your measurement :(

> Even querying 30d causes InfluxDB cloud to run out of memory. 

Try to insert this line protocols into database:

```
my-measurement,tag1=a field1=10 1
my-measurement,tag2=a field2=10 1605189244
```

If we specify the range to `-30d` we loose the `field1`.

> This will be the case for most customers who have significant data in their tables.

So we have to add an advance option into Connector configuration that will limit range in Schema query.

**Comment by bednar** [comment]
New option in Configuration screen:

_The range that is used for determine your InfluxDB data schema. -  https://todo_link_to_doc_
**Schema Range**
-30d

What do you think?

**Comment by gefaila** [comment]
I think the following flux query contains the necessary data and it completes in only a few sec while scanning *all* data.

>import "influxdata/influxdb/v1"
bucket = "my_bucket"
measurement = "my_measurement"
tags = v1.tagKeys(
  bucket: bucket,
  predicate: (r) => r._measurement == measurement,
  start: -100000d) 
  |> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
  |> findColumn(fn: (key) => true, column: "_value")
from(bucket: bucket) 
  |> range(start: -100000d) 
  |> filter(fn: (r) => r["_measurement"] == measurement) 
  |> drop(columns: ["_start", "_stop","_time"])
  |> unique(column: "_field")`

It contains tables that show for *everything*
_field,_value, #datatype, tags

Can you work with that to build the schema you need?

**Comment by bednar** [comment]
@gefaila nice catch 👍 Thanks!

I think the following query could be a solution:

```flux
import "influxdata/influxdb/v1"

bucket = "my-bucket"
measurement = "my-measurement"
start_range = duration(v: uint(v: 1970-01-01) - uint(v: now()))

v1.tagKeys(
  bucket: bucket,
  predicate: (r) => r._measurement == measurement,
  start: start_range
) |> filter(fn: (r) => r._value != "_start" and r._value != "_stop" and r._value != "_measurement" and r._value != "_field")
  |> yield(name: "tags")

from(bucket: bucket)
  |> range(start: start_range)
  |> filter(fn: (r) => r["_measurement"] == measurement)
  |> keep(fn: (column) => column == "_field" or column == "_value")
  |> unique(column: "_field")
  |> yield(name: "fields")
```

Could you try it with your data? If you could share a result of query it will be awesome.

**Comment by gefaila** [comment]
It works! 👍 
But there is no need for the 
>start_range = duration(v: uint(v: 1970-01-01) - uint(v: now()))

you only need
>start_range =-1000y

For me this returns the following

[2020-11-13-10-12_chronograf_data.zip](https://github.com/influxdata/influxdb-gds-connector/files/5536136/2020-11-13-10-12_chronograf_data.zip)

**Comment by gefaila** [comment]
Hi @bednar 
How's things progressing?
Were you able to use the returned data of that query to construct a usable schema?

**Comment by bednar** [comment]
Hi @gefaila,

I want start works on this as soon as possible ... probably at Thursday or Friday.

Thanks a lot with your help, the query is fine and we will use it 👍

Regards

**Comment by bednar** [comment]
Hi @gefaila,

you could track progress at #9

Regards

**Comment by gefaila** [comment]
Really really cool!
Thanks for delivering this. I think lots of people will love it!

I enjoyed oiling the creative cogs!!

Cheers
Andrew


On Fri, 20 Nov 2020 at 09:47, Jakub Bednář <notifications@github.com> wrote:


Hi @gefaila,

you could track progress at #9

Regards

**Comment by bednar** [comment]
Hi @gefaila,

there is prepared a test version of the Connector:

https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbySDF4eD7wmA_awZ6aoCwENuXs1Opw_T0DIJ8F-MVI

Could you test it with your schema?

**Comment by gefaila** [comment]
Hi  Jacub,
I'm sure it's a small thing .. but it's doesn't quite yet work.

I get

Community Connector Error

There was an error caused by the community connector. Please report the
issue to the provider of this community connector if this issue persists.
Connector details

"GetFields from: https://eu-central-1-1.aws.cloud2.influxdata.com" returned
an error:Exception: Argument too large: value

Error ID: 943f700f

**Comment by bednar** [comment]
It is caused by too large schema. We have to change how we cache the produced schema.

- https://developers.google.com/apps-script/reference/cache/cache#put(String,String)
- https://github.com/influxdata/influxdb-gds-connector/blob/55c416207d7f5f0b870ece10dbc5e5a870f9172d/src/Connector.js#L62

**Comment by gefaila** [comment]
> It is caused by too large schema. We have to change how we cache the produced schema.
> ...

I see.
I think my schema size is probably average for someone who is using InfluxDB in a real-world context.

**Comment by bednar** [comment]
Hi @gefaila, 

the commit https://github.com/influxdata/influxdb-gds-connector/pull/9/commits/118edfef9197edb111b5d5307108a891c9f7938d fixes: `Argument too large: value`

Could you try the fixed version?

https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbySDF4eD7wmA_awZ6aoCwENuXs1Opw_T0DIJ8F-MVI

> I think my schema size is probably average for someone who is using InfluxDB in a real-world context.

It is true, but Google Data Studio is like other visualisation and analytics tool - their loves well-structured data.

Here is nice article from Tableau - https://www.tableau.com/learn/get-started/data-structure

**Comment by gefaila** [comment]
I think influx tables fulfill all of that.

Can you explain what GDS needs the influx data to conform to? 

Do you have an example influx bucket that conforms to this? 

Can you give us a list that outlines in plain language the restrictions on influx buckets? 
E.g.
1) all records must have .....
2) ...

**Comment by gefaila** [comment]
I'm failing to see how our industrial IIOT data doesn't conform to this. Is there a specific problem that our data doesn't conform to that you can point to and clarify?

**Comment by bednar** [comment]
From my experience with GDS there are these constrains:

#### 1. Avoid unnecessary data
- every "widget" on the Google Data Studio Page uses connector to fetch data (even filter)
- is good to prepare "measurement view" only with data that you need to reduce overhead caused by network transmission and parsing result
- For example this report: https://datastudio.google.com/u/0/reporting/257a8b65-162c-4444-96a9-10b6c218074a/page/ZY4TB?s=p19vh-b82Sw is based on 3 datasets (measurement) but we use a Flux Task to prepare simple measurement with this schema:
![](https://raw.githubusercontent.com/influxdata/influxdb-gds-connector/master/examples/GDS-schema.png)

#### 2. Avoid `null` values
 - GDS doesn't like null values
- `100 + 23 + null + 7 = null`
- https://help.funnel.io/en/articles/2894841-how-do-i-avoid-null-values-when-exporting-calculated-fields-to-google-data-studio#how-does-data-studio-handle-null-values
- https://support.google.com/datastudio/thread/68235204?hl=en

#### 3. Avoid data blending
- https://support.google.com/datastudio/answer/9061420?hl=en&ref_topic=9061419
- it is nice feature but with impact to performance

#### 4. Data range 
- the default data range is -28days
- How you data looks like for this range? This query will be used by connector:
```flux
bucket = "my-bucket"
measurement = "my-repository"
  
start = -28d
stop = now()

from(bucket: bucket) 
 |> range(start: start, stop: stop) 
 |> filter(fn: (r) => r["_measurement"] == measurement) 
 |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```
 
Thanks you @gefaila to help us to improve our connector. Thanks again 👍
